# **Data Structure in Python**

# **1. List and Tuple**

Lists in Python are one of the most flexible and frequently used sequence data types. A list contains an ordered (indexed) collection of elements and can be changed (mutable). Here are some important points about lists in Python:

**a. Mutable (Can Be Modified)**

We can still make changes to data in a list because of its mutable nature, meaning its elements can be modified after the list is created.

**b. Ordered (Sequential)**

Ordered here means that to access data in a list, it will start sequentially according to the order of its index.

In [ ]:
list = ['uno', 'dos', 'tres', 'cuatro', 'cinco']
print(list[0])
print(list[1])
print(list[2])

uno
dos
tres

**c. Heterogeneous (Many Data Types)**

Lists are not rigid, meaning they can store values of various data types, as shown in the example below:

In [ ]:
list = ["data", 7, 1.25, 8, "mining", 5, False]
print(list)

['data', 7, 1.25, 8, 'mining', 5, False]

**d. Allow Duplicates**

Lists allow data with the same value because lists are influenced by their index.

In [ ]:
list = [1, "Maki", True, 1, "Jun", True]
print(list)

[1, 'Maki', True, 1, 'Jun', True]

**e. Dynamic**

Due to its mutable nature, lists allow operations on data. Operations that can be used on lists:

- Adding items

extend(): adds all iterable elements (such as a list, tuple, or string) one by one to the end of the list.

In [ ]:
list = [1, "Hiroshi", True]
list.extend(["Kazuki", 7, 2.15])
print(list)

[1, 'Hiroshi', True, 'Kazuki', 7, 2.15]

append(): adds a single element treated as one single object to the end of the list.

In [ ]:
list = [1, "Osamu", True]
list.append(["Ren", 7, 2.15])
print(list)

[1, 'Osamu', True, ['Ren', 7, 2.15]]

insert(): adds a new list to a specified position.

In the code below, we will insert a new list before index 2, which is before the True element.

In [ ]:
list = [1, "Osamu", True]
list.insert(2, ["Mugen", 7, 2.15])
print(list)

[1, 'Osamu', ['Mugen', 7, 2.15], True]

- Removing items

remove(): removes the first item in the list that matches the given value.

In [ ]:
fruits = ["Dewandaru", "Feijoa", "Abiu", "Black Sapote"]
fruits.remove("Black Sapote")
print(fruits)

['Dewandaru', 'Feijoa', 'Abiu']

If the remove command is executed again, the current value item will be removed.

In [ ]:
fruits.remove("Abiu")
print(fruits)

['Dewandaru', 'Feijoa']

pop(index): removes an item by its index and returns the removed item. If no index value is given, the last item will be removed.

In [ ]:
numbers = [10, 20, 30, 40, 50, 60, 70]

without_index = numbers.pop()
print("Pop without index:", numbers)
print("Removed:", without_index)

index = numbers.pop(2)
print("Pop with index:", numbers)
print("Removed:", index)

Pop without index: [10, 20, 30, 40, 50, 60]
Removed: 70
Pop with index: [10, 20, 40, 50, 60]
Removed: 30

clear(): removes all items from the list, making the list empty.

In [ ]:
names = ["Kazuki", "Takumi", "Jinpei"]
names.clear()
print(names)

[]

- Finding items

index(item): searches for the index of the first item that matches the given value.

In [ ]:
colors = ["Aka", "Ao", "Midori", "Ao"]
index = colors.index("Ao")
print(index)

1

- Counting items

count(item): counts the number of occurrences of an item in the list.

In [ ]:
scores = [10, 20, 10, 30, 10, 20, 10, 70, 10]
count = scores.count(10)
print(count)

# Output: 5

5

- Sorting items

sort(): sorts items in the list in ascending order by default, or descending if the parameter reverse=True is used.

In [ ]:
numbers = [10, 20, 10, 30, 10, 20, 10, 70, 10]
numbers.sort()  # Ascending
print(numbers)

numbers.sort(reverse=True)  # Descending
print(numbers)

[10, 10, 10, 10, 10, 20, 20, 30, 70]
[70, 30, 20, 20, 10, 10, 10, 10, 10]

- Reversing order

reverse(): reverses the order of elements in a list without regard to element values.

In [ ]:
letters = ["a", "b", "c", "d", 1, 4, True, 2, 3, 1]
letters.reverse()
print(letters)

[1, 3, 2, True, 4, 1, 'd', 'c', 'b', 'a']

## **1.2 Tuple**

A tuple is an ordered sequence of objects in Python that is **immutable**. Tuples are similar to lists, but the main difference is that elements within a tuple cannot be changed after they are defined. Tuples use parentheses '()', while lists use square brackets '[]'. Creating a tuple is very easy; we just need to write values separated by commas. Here are some important points about tuples in Python:

**a. Immutable**

Once successfully created, a tuple cannot be changed, including adding or deleting elements within it.

In [ ]:
tuple = ("a", "b", "c", "d", "e")
print(tuple)

tuple = ("z",) + tuple[1:]
print(tuple)

('a', 'b', 'c', 'd', 'e')
('z', 'b', 'c', 'd', 'e')

**b. Heterogeneous (Many Data Types)**

Tuples allow for different data types, similar to Lists.

In [ ]:
tuple = ("data", 7, 1.25, 8, "mining", 5, False)
print(tuple)

('data', 7, 1.25, 8, 'mining', 5, False)

**c. Ordered (Sequential)**

Tuples are ordered like Lists, meaning we can access individual data elements using their respective indices.

In [ ]:
tuple = (1, 2, 3, 4, 5)
print(tuple[1])
print(tuple[2])
print(tuple[3])

2
3
4

**d. Indexable**

Each item in a tuple can be accessed using its index.

In [ ]:
t = (10, 20, 30, 40)
print(t[0])
print(t[3])

10
40

**e. Allow Duplicates**

Tuples also allow data with the same value, similar to Lists, as they are influenced by indices.

In [ ]:
tuple = (True, 7, "Taro", "Taro", 7, True)
print(tuple)

(True, 7, 'Taro', 'Taro', 7, True)

# **2. NumPy and Array**

NumPy (Numerical Python) is a Python library used to manage large arrays, including multi-dimensional arrays. This library also provides various mathematical functions to simplify complex calculations on arrays. Arrays in NumPy are grid-shaped data structures specifically designed to store numerical data. Compared to Python lists, NumPy arrays are faster and more efficient in performing calculations because they have been optimized.

## **2.1 Array NumPy vs List Python**

| **Array NumPy**                 | **List Python**                     |
|----------------------------------|--------------------------------------|
| Fixed Size                    | Dynamic Size                      |
| Elements must have the same data type | Element types can be diverse           |
| Faster element-wise mathematical operations | Does not directly support operations    |

## **2.2 Creating Arrays in NumPy**

**a. 1D Array**

Creates a one-dimensional array used to store a list of linear data.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]

**b. 2D Array**

Creates a two-dimensional array that resembles a matrix or data table with rows and columns.

In [ ]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix)

[[1 2]
 [3 4]
 [5 6]]

**c. 3D Array**

Creates a three-dimensional array that can store complex data such as tensors in machine learning.

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

## **2.3 Array Properties**

**a. Array Dimension (ndim)**

Provides information about the number of array dimensions, e.g., 1D, 2D, or 3D.

**b. Array Shape**

Indicates the number of elements in each dimension (e.g., a 2x3 array has a shape of (2, 3)).

**c. Number of Elements (size)**

Returns the total number of elements in the array.

**d. Data Type (dtype)**

Describes the data type used by the array, such as int32 or float64.

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", array.ndim)
print("Shape:", array.shape)
print("Number of Elements:", array.size)
print("Data Type:", array.dtype)

Dimensions: 2
Shape: (2, 3)
Number of Elements: 6
Data Type: int64

## **2.4 Mathematical Operations on Arrays**

**a. Element-wise Operations**

Performs mathematical operations such as addition, multiplication, or exponentiation on array elements directly, element by element.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Output: [5 7 9]
print(a * b)  # Output: [4 10 18]
print(a ** 2) # Output: [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]

**b. Matrix Operations**

Performs linear algebra operations useful for large-scale numerical data manipulation.

- Matrix Addition and Subtraction

Addition and subtraction of two matrices can only be performed if both have the same size.

In [ ]:
import numpy as np

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Addition
print(mat1 + mat2)

# Substraction
print(mat2 - mat1)

[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]

- Matrix Multiplication

Matrix multiplication can be performed as:

**Element-wise Multiplication:**

Multiplies corresponding elements in two matrices (operator * in NumPy).

**Matrix Multiplication**

Standard linear multiplication where elements are calculated as the result of multiplying rows and columns (using the np.dot() function or the @ operator).

In [ ]:
import numpy as np

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Element-wise Multiplication
print(mat1 * mat2)

# Matrix Multiplication
print(np.dot(mat1, mat2))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]

## **2.5 Indexing and Slicing**

Like Python lists, NumPy arrays support accessing individual elements and subsets of elements using indices. This feature is very flexible, even allowing manipulation of partial data without affecting the original data.

In [ ]:
array = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(array[0])
print(array[-1])

# Slicing
print(array[1:4])
print(array[:3])

1
5
[2 3 4]
[1 2 3]

## **2.6 Reshaping**

Reshaping is used to change the shape of an array without changing its data. For example, you can change a 1D array to 2D or vice versa.

Main Functions:

- reshape(): Changes the shape of the array to the desired dimension.
- flatten(): Converts a multi-dimensional array into a 1D array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Convert to 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array:")
print(reshaped_arr)

# Convert back to 1D array
flattened_arr = reshaped_arr.flatten()
print("\nFlattened Array:")
print(flattened_arr)

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]

## **2.7 Concatenating Arrays**

Concatenating arrays means combining several arrays into one, either horizontally (row-wise) or vertically (column-wise).

Main Functions:

- np.concatenate(): Concatenates arrays along a specified axis.
- np.vstack(): Stacks arrays vertically (rows increase).
- np.hstack(): Stacks arrays horizontally (columns increase).

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Merge vertically
vertical_concat = np.vstack((arr1, arr2))
print("Vertical Concatenation:")
print(vertical_concat)

# Merge horizontally
horizontal_concat = np.hstack((arr1, arr2))
print("\nHorizontal Concatenation:")
print(horizontal_concat)

Vertical Concatenation:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Concatenation:
[[1 2 5 6]
 [3 4 7 8]]

## **2.8 Splitting**

Array splitting means dividing one array into several smaller arrays with a certain number of elements.

Main Functions:

- np.split(): Splits an array at specified indices.
- np.vsplit(): Splits vertically.
- np.hsplit(): Splits horizontally.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Divide horizontally into two parts
horizontal_split = np.hsplit(arr, 2)
print("Horizontal Splitting:")
print(horizontal_split[0])  # First part
print(horizontal_split[1])  # Second part

# Divide vertically into two parts
vertical_split = np.vsplit(arr, 2)
print("\nVertical Splitting:")
print(vertical_split[0])  # First part
print(vertical_split[1])  # Second part

Horizontal Splitting:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]

Vertical Splitting:
[[1 2 3 4]]
[[5 6 7 8]]

# **3. Pandas Dataframe**

Pandas is a very useful Python library for data analysis and processing, suitable for handling datasets from medium to large sizes. In Pandas, there are two main types of data structures:

a. Series: A one-dimensional array that can store various types of data and has an axis label.

b. DataFrame: A two-dimensional data structure, similar to a table with rows and columns, that can store various types of data and also has axis labels.

Some key advantages and features of Pandas are:

a. Fast Data Loading: Can easily load data from various sources such as CSV files, Excel, or databases.

b. Efficient Data Manipulation: Offers various functions and methods for cleaning, sorting, and restructuring data in a highly effective way.

c. Data Merging: Allows easy merging and grouping of data, similar to SQL join operations.

d. Various Built-in Functions: Provides many functions for comprehensive data aggregation, transformation, and analysis.

## **3.1  Creating a DataFrame from a Simple Array**

Creating a DataFrame from a Simple Array is one of the basic ways to use the Pandas library for data manipulation and analysis.

In [ ]:
import pandas as pd

# Calling the dataframe constructor
dataframe = pd.DataFrame()
print(dataframe) # Empty dataframe

# Create a list containing strings
words = ['this', 'is', 'dataframe']

# Calling the dataframe constructor on a list
dataframe = pd.DataFrame(words)
print("\n", dataframe)

Empty DataFrame
Columns: []
Index: []

            0
0       this
1         is
2  dataframe

## **3.2 Creating a DataFrame from a Python Dictionary**

A Python dictionary is a data structure consisting of key-value pairs, where keys can be used as column names within a DataFrame. By using a dictionary, users can easily organize data and create a neat DataFrame, allowing for more efficient data manipulation and analysis.

In [ ]:
import pandas as pd

myvar = pd.DataFrame()
print(myvar) # The dataframe is empty

mydataset = {
  'Name': ["Yui", "Mio", "Ritsu", "Tsumugi", "Azusa"],
  'Height': [156, 160, 154, 157, 150]
}

# Calling the dataframe constructor on a list
myvar = pd.DataFrame(mydataset)
print(myvar)

Empty DataFrame
Columns: []
Index: []
      Name  Height
0      Yui     156
1      Mio     160
2    Ritsu     154
3  Tsumugi     157
4    Azusa     150

# **CODELAB**

**CODELAB 1**

a. Create 12 data tuples, each containing 4 int, float, and string data in random order.

b. Convert the tuple data into a list.

c. Add 2 new data points at the index corresponding to your last NIM digit (if the last NIM digit is 0, then index 10).

d. Remove float data types from the list.

e. Sort the elements in the list in descending order.

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
import random

data_tuples = []
for _ in range(12):
    t = (random.randint(1, 100), random.uniform(1.0, 50.0), "Data", "Mining")
    data_tuples.append(t)
print("Data Tuples (12 buah):")
print(data_tuples)

Data Tuples (12 buah):
[(76, 2.5247925758865843, 'Data', 'Mining'), (27, 33.719039560398734, 'Data', 'Mining'), (50, 36.94593352336722, 'Data', 'Mining'), (1, 10.14987297044772, 'Data', 'Mining'), (7, 10.268868092960911, 'Data', 'Mining'), (87, 14.74770659700785, 'Data', 'Mining'), (50, 30.975323152989876, 'Data', 'Mining'), (77, 32.217715675271265, 'Data', 'Mining'), (67, 25.482718710963688, 'Data', 'Mining'), (50, 44.59401912407895, 'Data', 'Mining'), (29, 19.084785263024106, 'Data', 'Mining'), (19, 22.296286811602517, 'Data', 'Mining')]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
data_list = [item for t in data_tuples for item in t]
print("Data List (Hasil Konversi):")
print(data_list)

Data List (Hasil Konversi):
[67, 21.76307519958005, 'Data', 'Mining', 21, 15.303106926479195, 'Data', 'Mining', 27, 42.346264281437726, 'Data', 'Mining', 47, 26.767885598239786, 'Data', 'Mining', 40, 13.33909081756682, 'Data', 'Mining', 69, 18.26358445728142, 'Data', 'Mining', 48, 15.200958995761942, 'Data', 'Mining', 16, 17.703593055826587, 'Data', 'Mining', 85, 6.39647805350448, 'Data', 'Mining', 22, 4.0908825506747695, 'Data', 'Mining', 95, 35.219724225070394, 'Data', 'Mining', 32, 30.95436781147723, 'Data', 'Mining']

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
data_list.insert(2, "BARU_1")
data_list.insert(3, "BARU_2")
print("List setelah ditambah data baru:")
print(data_list)

List setelah ditambah data baru:
[67, 21.76307519958005, 'BARU_1', 'BARU_2', 'Data', 'Mining', 21, 15.303106926479195, 'Data', 'Mining', 27, 42.346264281437726, 'Data', 'Mining', 47, 26.767885598239786, 'Data', 'Mining', 40, 13.33909081756682, 'Data', 'Mining', 69, 18.26358445728142, 'Data', 'Mining', 48, 15.200958995761942, 'Data', 'Mining', 16, 17.703593055826587, 'Data', 'Mining', 85, 6.39647805350448, 'Data', 'Mining', 22, 4.0908825506747695, 'Data', 'Mining', 95, 35.219724225070394, 'Data', 'Mining', 32, 30.95436781147723, 'Data', 'Mining']

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# D
data_list = [x for x in data_list if not isinstance(x, float)]
print("List setelah menghapus float:")
print(data_list)

List setelah menghapus float:
[67, 'BARU_1', 'BARU_2', 'Data', 'Mining', 21, 'Data', 'Mining', 27, 'Data', 'Mining', 47, 'Data', 'Mining', 40, 'Data', 'Mining', 69, 'Data', 'Mining', 48, 'Data', 'Mining', 16, 'Data', 'Mining', 85, 'Data', 'Mining', 22, 'Data', 'Mining', 95, 'Data', 'Mining', 32, 'Data', 'Mining']

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# E
data_list.sort(key=str, reverse=True)
print("List urutan descending:")
print(data_list)

List urutan descending:
['Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Mining', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'Data', 'BARU_2', 'BARU_1', 95, 85, 69, 67, 48, 47, 40, 32, 27, 22, 21, 16]

**CODELAB 2**

a. Create a 2D array based on the last 6 digits of your student ID (NIM).

b. Perform addition, subtraction, and multiplication operations on the matrix you created.

c. Convert the matrix into a 1D shape.

d. Perform slicing on the matrix.

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
import numpy as np
nim_6 = np.array([3, 1, 1, 0, 4, 2])
matrix = nim_6.reshape(2, 3)
print("Matrix 2D (311042):\n", matrix)

Matrix 2D (311042):
 [[3 1 1]
 [0 4 2]]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
dummy = np.array([[1, 2, 3], [4, 5, 6]])
print("Penjumlahan:\n", matrix + dummy)
print("Pengurangan:\n", matrix - dummy)
print("Perkalian:\n", matrix * dummy)

Penjumlahan:
 [[4 3 4]
 [4 9 8]]
Pengurangan:
 [[ 2 -1 -2]
 [-4 -1 -4]]
Perkalian:
 [[ 3  2  3]
 [ 0 20 12]]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
matrix_1d = matrix.flatten()
print("Matrix 1D Shape:", matrix_1d)

Matrix 1D Shape: [3 1 1 0 4 2]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# D
sliced = matrix[0, 1:]
print("Hasil Slicing:", sliced)

Hasil Slicing: [1 1]

**CODELAB 3**

a. Create a series containing a dictionary that includes product names and product IDs.

b. Create a dataframe containing a dictionary with 4 columns, and each column contains 5 data points. There should be no similarities between students.

c. Add 1 new column.

d. Sort the dataframe, for example, alphabetically if the column is 'Name'.

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
import pandas as pd
product_dict = {'Laptop': 'P01', 'Mouse': 'P02', 'Keyboard': 'P03'}
series_prod = pd.Series(product_dict)
print(series_prod)

Laptop      P01
Mouse       P02
Keyboard    P03
dtype: object

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
data = {
    'Nama': ['A', 'B', 'C', 'D', 'E'],
    'ID': [101, 102, 103, 104, 105],
    'Skor': [80, 85, 90, 75, 88],
    'Kelas': ['X', 'Y', 'X', 'Z', 'Y']
}
df = pd.DataFrame(data)
print(df)

  Nama   ID  Skor Kelas
0    A  101    80     X
1    B  102    85     Y
2    C  103    90     X
3    D  104    75     Z
4    E  105    88     Y

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
df['Status'] = ['Aktif', 'Aktif', 'Nonaktif', 'Aktif', 'Aktif']
print(df)

  Nama   ID  Skor Kelas    Status
0    A  101    80     X     Aktif
1    B  102    85     Y     Aktif
2    C  103    90     X  Nonaktif
3    D  104    75     Z     Aktif
4    E  105    88     Y     Aktif

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# D
df_sorted = df.sort_values(by='Nama', ascending=True)
print("Dataframe Sorted:")
print(df_sorted)

Dataframe Sorted:
  Nama   ID  Skor Kelas    Status
0    A  101    80     X     Aktif
1    B  102    85     Y     Aktif
2    C  103    90     X  Nonaktif
3    D  104    75     Z     Aktif
4    E  105    88     Y     Aktif

# **ASSIGNMENT**

**ASSIGNMENT 1**

Create a function that accepts a list as a parameter and performs the following operations:

1. Add 10 random numeric elements (int and float).
2. Remove elements at the index according to your student ID (odd/even).
3. Reverse the order of elements in the list.
4. Remove the element with the largest value from the list.
5. Sort the elements in the list in descending order.

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
import random
# Asumsi input_list awal
my_list = [10, 20, 30, 40]

for _ in range(5):
    my_list.append(random.randint(1, 100)) # int
    my_list.append(round(random.uniform(1.0, 100.0), 2)) # float
print("List setelah ditambah 10 data acak:")
print(my_list)

List setelah ditambah 10 data acak:
[10, 20, 30, 40, 59, 4.21, 86, 3.06, 45, 26.98, 75, 33.28, 47, 21.2]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
# NIM akhir 2, maka hapus indeks ke-2
if len(my_list) > 2:
    removed_val = my_list.pop(2)
    print(f"Elemen '{removed_val}' pada indeks 2 telah dihapus.")
print(my_list)

Elemen '30' pada indeks 2 telah dihapus.
[10, 20, 40, 59, 4.21, 86, 3.06, 45, 26.98, 75, 33.28, 47, 21.2]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
my_list.reverse()
print("Hasil (c) - List setelah dibalik (reversed):")
print(my_list)

Hasil (c) - List setelah dibalik (reversed):
[21.2, 47, 33.28, 75, 26.98, 45, 3.06, 86, 4.21, 59, 40, 20, 10]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# D
# Filter angka saja agar max() tidak error
numeric_only = [x for x in my_list if isinstance(x, (int, float))]
if numeric_only:
    max_val = max(numeric_only)
    my_list.remove(max_val)
    print(f"Hasil (d) - Nilai terbesar ({max_val}) dihapus:")
print(my_list)

Hasil (d) - Nilai terbesar (86) dihapus:
[21.2, 47, 33.28, 75, 26.98, 45, 3.06, 4.21, 59, 40, 20, 10]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# E
my_list.sort(key=str, reverse=True)
print("Hasil (e) - Urutan Descending Akhir:")
print(my_list)

Hasil (e) - Urutan Descending Akhir:
[75, 59, 47, 45, 40, 4.21, 33.28, 3.06, 26.98, 21.2, 20, 10]

**ASSIGNMENT 2**

Create a tuple containing a dictionary with 10 key-value pairs of courses and grades. Among these 10 key-value pairs, ensure that at least 3 have empty values. Perform the following operations:

1. Remove incomplete entries or those with empty values.
2. Count the number of entries remaining after deletion.
3. Sort the key-value pairs by value in ascending order.
4. Find the course with the highest grade.
5. Calculate the average of all course grades.

In [ ]:
# Membuat list yang berisi dictionary untuk 10 mata kuliah
data_courses = [
    {"subject": "Matematika", "grade": 85},
    {"subject": "IPA", "grade": 90},
    {"subject": "IPS", "grade": None},
    {"subject": "B.Indo", "grade": 88},
    {"subject": "B.Inggris", "grade": None},
    {"subject": "Fisika", "grade": 75},
    {"subject": "Kimia", "grade": 80},
    {"subject": "Biologi", "grade": None},
    {"subject": "Sejarah", "grade": 82},
    {"subject": "Ekonomi", "grade": 84}
]
print("Data Awal (List of Dictionaries):")
print(data_courses)

Data Awal (List of Dictionaries):
[{'subject': 'Matematika', 'grade': 85}, {'subject': 'IPA', 'grade': 90}, {'subject': 'IPS', 'grade': None}, {'subject': 'B.Indo', 'grade': 88}, {'subject': 'B.Inggris', 'grade': None}, {'subject': 'Fisika', 'grade': 75}, {'subject': 'Kimia', 'grade': 80}, {'subject': 'Biologi', 'grade': None}, {'subject': 'Sejarah', 'grade': 82}, {'subject': 'Ekonomi', 'grade': 84}]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
# Menghapus dictionary yang nilainya None pada key 'grade'
cleaned_data = [course for course in data_courses if course['grade'] is not None]
print("Data setelah entri tidak lengkap dihapus:")
print(cleaned_data)

Data setelah entri tidak lengkap dihapus:
[{'subject': 'Matematika', 'grade': 85}, {'subject': 'IPA', 'grade': 90}, {'subject': 'B.Indo', 'grade': 88}, {'subject': 'Fisika', 'grade': 75}, {'subject': 'Kimia', 'grade': 80}, {'subject': 'Sejarah', 'grade': 82}, {'subject': 'Ekonomi', 'grade': 84}]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
# Menghitung jumlah data yang tersisa di dalam list
count_data = len(cleaned_data)
print(f"Jumlah data yang tersisa: {count_data}")

Jumlah data yang tersisa: 7

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
# Mengurutkan list of dictionary berdasarkan nilai grade (Ascending)
cleaned_data.sort(key=lambda x: x['grade'])
print("Data setelah diurutkan berdasarkan nilai:")
print(cleaned_data)

Data setelah diurutkan berdasarkan nilai:
[{'subject': 'Fisika', 'grade': 75}, {'subject': 'Kimia', 'grade': 80}, {'subject': 'Sejarah', 'grade': 82}, {'subject': 'Ekonomi', 'grade': 84}, {'subject': 'Matematika', 'grade': 85}, {'subject': 'B.Indo', 'grade': 88}, {'subject': 'IPA', 'grade': 90}]

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# D
# Mencari mata kuliah dengan grade tertinggi
highest_entry = max(cleaned_data, key=lambda x: x['grade'])
print(f"Hasil (d) - Tertinggi: {highest_entry['subject']} dengan nilai {highest_entry['grade']}")

Hasil (d) - Tertinggi: IPA dengan nilai 90

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# E
# Menghitung rata-rata
total_grade = sum(course['grade'] for course in cleaned_data)
average_grade = total_grade / len(cleaned_data)
print(f"Hasil (e) - Rata-rata nilai: {average_grade:.2f}")

Hasil (e) - Rata-rata nilai: 83.43

**ASSIGNMENT 3**

Create a dataframe consisting of 10 rows and 6 columns, with the following information:

| | Brand | Branch | Price (thousand) | Stock | Status |
|--|---|---|---|---|---|
| 1 | Avoskin | Surabaya | 150 | 175 | Sold |
| 2 | G2G | Jakarta Pusat | 75 | 160 | Available |
| 3 | Skintific | Bandung | 120 | 120 | Available
| 4 | Wardah | Bandung | 85 | 300 | Sold |
| 5 | Emina | Jakarta | 75 | 230 | Available |
| 6 | Somethinc | Bandung | 120 | 200 | Available |
| 7 | Azarine | Surabaya | 50 | 180 |Available |
| 8 | Lacoco | Bandung | 90 | 100 | Sold |
| 9 | Y.O.U | Jakarta Pusat | 55 | 180 |Available |
| 10 | Madame Gie | Surabaya | 50 | 200 | Sold |

Perform the following analysis on the DataFrame:

1. Display a summary of descriptive statistics including minimum, maximum, sum, mean, standard deviation, and quartile 1, 2, and 3 values.
2. Identify the top 3 brands with the largest revenue (price x stock).
3. Group brands with the same price.
4. Create a new column containing categories 'Cheap', 'Medium', and 'Expensive'. These categories are based on the following rules:
- Prices below quartile 1 are categorized as 'Cheap'.
- Prices above quartile 3 are categorized as 'Expensive'.
- The rest are categorized as 'Medium'.

In [ ]:
import pandas as pd

# Data disesuaikan persis dengan tabel yang lu kirim
data_skincare = {
    'Brand': ['Avoskin', 'G2G', 'Skintific', 'Wardah', 'Emina', 'Somethinc', 'Azarine', 'Lacoco', 'Y.O.U', 'Madame Gie'],
    'Branch': ['Surabaya', 'Jakarta Pusat', 'Bandung', 'Bandung', 'Jakarta', 'Bandung', 'Surabaya', 'Bandung', 'Jakarta Pusat', 'Surabaya'],
    'Price': [150, 75, 120, 85, 75, 120, 50, 90, 55, 50],
    'Stock': [175, 160, 120, 300, 230, 200, 180, 100, 180, 200],
    'Status': ['Sold', 'Available', 'Available', 'Sold', 'Available', 'Available', 'Available', 'Sold', 'Available', 'Sold']
}

df = pd.DataFrame(data_skincare)
print("Dataframe Skincare Berhasil Dibuat (Sesuai Tabel):")
df

Dataframe Skincare Berhasil Dibuat (Sesuai Tabel):

        Brand         Branch  Price  Stock     Status
0     Avoskin       Surabaya    150    175       Sold
1         G2G  Jakarta Pusat     75    160  Available
2   Skintific        Bandung    120    120  Available
3      Wardah        Bandung     85    300       Sold
4       Emina        Jakarta     75    230  Available
5   Somethinc        Bandung    120    200  Available
6     Azarine       Surabaya     50    180  Available
7      Lacoco        Bandung     90    100       Sold
8       Y.O.U  Jakarta Pusat     55    180  Available
9  Madame Gie       Surabaya     50    200       Sold

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# A
# Menampilkan deskripsi statistik untuk kolom Price (min, max, sum, mean, std, quartile)
price_stats = df['Price'].describe()
total_price = df['Price'].sum()

print("Statistik Deskriptif Kolom Price:")
print(price_stats)
print(f"\nTotal Sum dari Price: {total_price}")

Statistik Deskriptif Kolom Price:
count     10.000000
mean      87.000000
std       33.681515
min       50.000000
25%       60.000000
50%       80.000000
75%      112.500000
max      150.000000
Name: Price, dtype: float64

Total Sum dari Price: 870

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# B
# Revenue = Price * Stock
df['Revenue'] = df['Price'] * df['Stock']
top_3_revenue = df.nlargest(3, 'Revenue')

print("Top 3 Brand Skincare dengan Revenue Terbesar:")
top_3_revenue[['Brand', 'Revenue']]

Top 3 Brand Skincare dengan Revenue Terbesar:

       Brand  Revenue
0    Avoskin    26250
3     Wardah    25500
5  Somethinc    24000

In [ ]:
# Hilmi Haidar Anwar
# 202310370311042
# C
# Mengelompokkan brand yang memiliki harga yang sama
grouped_brands = df.groupby('Price')['Brand'].apply(list)

print("Brand Skincare dengan harga yang sama:")
print(grouped_brands)

Brand Skincare dengan harga yang sama:
Price
50      [Azarine, Madame Gie]
55                    [Y.O.U]
75               [G2G, Emina]
85                   [Wardah]
90                   [Lacoco]
120    [Skintific, Somethinc]
150                 [Avoskin]
Name: Brand, dtype: object

In [ ]:
# Hilmi Haidar Anwar
# 20231070311042
# D
# Kategori berdasarkan Quartile 1 (Q1) dan Quartile 3 (Q3)
q1 = df['Price'].quantile(0.25)
q3 = df['Price'].quantile(0.75)

def categorize_price(p):
    if p < q1:
        return 'Cheap'
    elif p > q3:
        return 'Expensive'
    else:
        return 'Medium'

df['Price_Category'] = df['Price'].apply(categorize_price)
print(f"Batas Kuartil -> Q1 (Cheap): {q1}, Q3 (Expensive): {q3}")
print("\nHasil Akhir Tabel dengan Kategori Harga:")
df[['Brand', 'Price', 'Price_Category']]

Batas Kuartil -> Q1 (Cheap): 60.0, Q3 (Expensive): 112.5

Hasil Akhir Tabel dengan Kategori Harga:

        Brand  Price Price_Category
0     Avoskin    150      Expensive
1         G2G     75         Medium
2   Skintific    120      Expensive
3      Wardah     85         Medium
4       Emina     75         Medium
5   Somethinc    120      Expensive
6     Azarine     50          Cheap
7      Lacoco     90         Medium
8       Y.O.U     55          Cheap
9  Madame Gie     50          Cheap